language: node_js
node_js:
  - stable
before_install:
  - npm install -g pnpm coveralls codacy-coverage
install:
  - pnpm install
script:
  - pnpm run test-coverage -- --coverageReporters=text-lcov | tee coveralls | codacy-coverage
